version: '3.8'

services: 
  node_backend:
    container_name: node-web-app
    image: node-web-app
    build: 
      context: .
    ports:
      - "3000:3000"
    environment: 
      - EXTERNAL_PORT=3000
      - PGDATABASE=test
      - PGUSER=postgres
      - PGPASSWORD=h
      - PGHOST=node_db
    networks:
      - cnp2_net
    depends_on: 
      - node_db
  node_db: 
    container_name: node_db
    image: "postgres"
    
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=h
      - POSTGRES_DB=test
    volumes:
      - ./src/tablas.sql:/docker-entrypoint-initdb.d/tablas.sql
    networks:
      - cnp2_net

volumes:
 nps_data: {}

networks:
 cnp2_net:
